### ISSUE TITLE
Can I use these code to extract flow features from my own videos?

### ISSUE THREAD

**Issue by sharontaozi** [CMU-CREATE-Lab/deep-smoke-machine#1]
Hi,I want to extract flow features(pre-train on Kinetics) from another dataset (MSVD).Can I use these code to arrive the target?

**Comment by yenchiah** [comment]
The short answer is no. Currently, the code extracts i3d features from rgb frames, not flow frames. We are working on extracting i3d flow features, which will probably take one or two more weeks.

**Comment by sharontaozi** [comment]
Thank you ! I will pay attention to this project.
