### ISSUE TITLE
How can I train all the process video with the train.py model?

### ISSUE THREAD

**Issue by changyangmimeng** [CMU-CREATE-Lab/deep-smoke-machine#12]
Dear author:

I use the poject to reappear the results.But when i extract the i3d-rgb/i3d-flow to train the model with the features, then train running interface disappeared suddenly .I monitored the systems of PC, the cpu and memory is full at that running time. Also the process extract the features occupy harddisk storage space larger and larrger.So i want to say my pc if could run the code and what parameter of hardware could run the project? My pc configuration as below：
cpu：amd R9 5900X
memory：32G
harddisk：260G
OS：unbuntu 22
GPU：RTX 3090 24G
Kindly hope your reply soon. Thank you very much!

**Comment by yenchiah** [comment]
(sorry somehow I missed this issue)

The computer that I used has 128 GB memory (or 64 GB, cannot remember exactly). The storage is 1 TB SSD (or 2 TB, also cannot remember exactly).

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！
