### ISSUE TITLE
Why can't you download metadata now？

### ISSUE THREAD

**Issue by 10652835** [CMU-CREATE-Lab/deep-smoke-machine#2]
![image](https://user-images.githubusercontent.com/29936727/61275439-8eb12e00-a7e0-11e9-8299-8a0348ff71ff.png)
I get the user-token from the gallery,but I still can't download the metadata

**Comment by yenchiah** [comment]
Sorry that we are still curating the dataset because it is not ready for releasing yet. The data now is only available for our internal developers.
