### ISSUE TITLE
How can I get the user token?

### ISSUE THREAD

**Issue by Goolo2** [CMU-CREATE-Lab/deep-smoke-machine#5]
Dear author,

I have gained a lot from your paper, and I appreciate your pioneering work. But how can I get the user token? I am eager to do further research on the basis of your work.

Thank you very much!

**Comment by yenchiah** [comment]
You can use our publicly released dataset without the user token. I have updated the README file to address this confusion. The process is documented in the first paragraph of the "Use this tool" section in the README file.

**Comment by Goolo2** [comment]
> You can use our publicly released dataset without the user token. I have updated the README file to address this confusion. The process is documented in the first paragraph of the "Use this tool" section in the README file.

OK, thank you very much !
