### ISSUE TITLE
Download Panoramas

### ISSUE THREAD

**Issue by dariogonle** [CMU-CREATE-Lab/deep-smoke-machine#7]
is it possible to download all viodes panoramas? I would like to download the 3, but not just for 3 seconds, I would like to download the whole video.

**Comment by yenchiah** [comment]
Yes. You can download the video panoramas from [http://mon.createlab.org/](http://mon.createlab.org/)

**Comment by dariogonle** [comment]
Thank you for answering, but I don't see a download button or something similar to dowload it. I also think that the clips obtained  by running python download_videos.py have a better quality, it this right or am I imagining it?

Does it exist and API to download it? Is it possible to select a period of time, I mean 2019-04-15 10:00:00 to 2019-04-15 10:01:00?


This is what I'am seeing:
![image](https://user-images.githubusercontent.com/80393891/117698999-9c5d5200-b1c4-11eb-8e0b-585ada55eb87.png)


Thank you.

**Comment by yenchiah** [comment]
You can click on the "share" button to bring up an user interface that allows generating videos with arbitrary size. To automate the video downloading, you will need to write a script. You can probably check [the script that I used for cropping the panoramas](https://github.com/CMU-CREATE-Lab/video-labeling-tool/blob/master/back-end/www/add_community_videos.py) for some inspirations. Here is the [API documentation](https://github.com/CMU-CREATE-Lab/timemachine-thumbnail-server) for downloading the video panoramas.

**Comment by dariogonle** [comment]
Thank you so much
