### ISSUE TITLE
Is it possible to download a complete panorama image?

### ISSUE THREAD

**Issue by dariogonle** [CMU-CREATE-Lab/deep-smoke-machine#8]
Hi, 
 
 I would like to download a complete panorama image like this one:
![cam_0](https://user-images.githubusercontent.com/80393891/119729680-3a177900-be75-11eb-965a-6bd3ca670439.png)

I've been using this http://mon.createlab.org/# to try to download it, but I can't get it.

Thank you.

**Comment by yenchiah** [comment]
You can click on the "share" button at the bottom right of the interface that shows the videos. Then, click on the "Share as image or video" tab.

![image](https://user-images.githubusercontent.com/1192071/119732798-f45caf80-be78-11eb-89a7-d6e70fad4445.png)

**Comment by dariogonle** [comment]
Thank you.
