### ISSUE TITLE
RuntimeError: no valid convolution algorithms available in CuDNN

### ISSUE THREAD

**Issue by Gmlearner231** [CMU-CREATE-Lab/deep-smoke-machine#9]
hi，I encounter this error when i run this program.emmm..  where can i set the"torch.backends.cudnn.benchmark"?

![image](https://user-images.githubusercontent.com/88812182/129131926-c83648f9-df95-4ba7-a248-e09b3c358def.png)

**Comment by yenchiah** [comment]
Hi, could you let me know the terminal commands that you run to get this error please?

**Comment by Gmlearner231** [comment]
Hi,the terminal commands is "python extract_features.py i3d-rgb",and I have skipped this question by disabling cudnn.Thanks for your reply.

**Comment by Lucky-LR** [comment]
Hello! I want to download your datasets. But I can not find a useful link. Can only download the codes?

**Comment by yenchiah** [comment]
To download the dataset please refer to the documentation in https://github.com/CMU-CREATE-Lab/deep-smoke-machine#use-this-tool (thanks!)
